# suppressPackageStartupMessages({
  library(shiny)
  library(shinyjs)
  library(bslib)
  library(dplyr)
  library(archive)
  library(doParallel)
  library(foreach)
  library(minfi)
  library(DMRcate)
  library(readxl)
  library(tools)
  library(readr)
  library(limma)
  library(foreach)
  library(ggplot2)
  library(ggpubr)
  library(ggrepel)
  library(plotly)
  library(grid)
  library(DT)
  library(gridExtra)
  library(bluster)
  library(BiocNeighbors)
  library(ComplexHeatmap)
  library(ConsensusClusterPlus)
  library(matrixStats)
  library(RColorBrewer)
  library(viridis)
  library(svglite)
  library(colorspace)
  # library(IlluminaHumanMethylation450kmanifest)
  # library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
  # library(IlluminaHumanMethylationEPICmanifest)
  library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
  # library(IlluminaHumanMethylationEPICv2manifest)
  # library(IlluminaHumanMethylationEPICv2anno.20a1.hg38)
# })



